title: Lucas Yamamoto
email: lucasayb97@gmail.com
sort_direction: desc
description: >- # this means to ignore newlines until "baseurl:"
  Sou um desenvolvedor Web e CTO da CodeBy. 
  Busco estar por dentro das tecnologias no mercado de e-commerce
  e programação no geral, sempre focando em me renovar e buscar por
  soluções úteis e práticas para mim e para as empresas para as quais
  prestamos serviços. 
baseurl: ""
url: "https://www.lucasyamamoto.com" 
twitter_username: lucasayb
github_username:  lucasayb
linkedin_username:  lucasayb
instagram_username:  lucasyamamoto1997

disqus_shortname: lucas-yamamoto

per_page: 10