backend:
  name: github
  repo: lucasayb/lucasyamamoto.golang
  branch: main
  site_domain: lucasyamamoto-golang.netlify.app

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Development",
              "DevOps",
              "Tips",
              "Experience",
              "Project Management",
              "Life",
              "Videos",
              "TV Shows",
            ],
        }
      - {
          label: "Color",
          name: "color",
          widget: "select",
          options:
            [
              { label: "Development", value: "#e74c3c" },
              { label: "DevOps", value: "#9b59b6" },
              { label: "Tips", value: "#1abc9c" },
              { label: "Experience", value: "#341f97" },
              { label: "Project Management", value: "#B53471" },
              { label: "Life", value: "#6ab04c" },
              { label: "Videos", value: "#3498db" },
              { label: "TV Shows", value: "#7f0b0b" },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Redirect from", name: "redirect_from", widget: "list" }

  - name: "pages"
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}