name: Trigger Netlify Build

on:
  schedule:
    - cron: '00 19 * * *' # Runs at midnight UTC. Adjust the schedule as needed.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/65ca6907e5df343e1c65b69f
